
### POST request to localhost to createUser

POST http://localhost:8080/users/createUser
Content-Type: application/json

{
  "username": "bob",
  "email": "bob@bobinson.com",
  "password": "supersecurepassword"
}

###GET all users again

GET http://localhost:8080/users/allUsers
Content-Type: application/json

### POST request to localhost to create second user

POST http://localhost:8080/users/createUser
Content-Type: application/json

{
  "username": "ben",
  "email": "ben@bobinson.com",
  "password": "supersecurepassword"
}

###GET all users again

GET http://localhost:8080/users/allUsers
Content-Type: application/json

###POST User creates Poll

POST http://localhost:8080/polls/createPoll
Content-Type: application/json

{
  "question": "What is a better letter?",
  "voteOptions": [
    { "caption": "A", "presentationOrder": 1 },
    { "caption": "B", "presentationOrder": 2 }
  ],
  "publishedBy": "73ef6632-20ad-463b-9955-0738601e3f17"
}

###GET all polls

GET http://localhost:8080/polls/allPolls
Content-Type: application/json

###POST User votes

POST http://localhost:8080/votes/castVote
Content-Type: application/json

{
  "userId": "ca3dfed2-71a9-4d1f-8f42-44cdddeca170",
  "pollId": "0492ea12-4d66-4db0-a572-febc1270206e",
  "voteOptionId": "73ef6632-20ad-463b-9955-0738601e3f17"
}

###POST User votes

POST http://localhost:8080/votes/castVote
Content-Type: application/json

{
  "userId": "d582ba25-e12e-49fb-a703-ffe53671544d",
  "pollId": "e3bb00ba-52c6-4fad-9fef-41f5a406cff7",
  "voteOptionId": "73ef6632-20ad-463b-9955-0738601e3f17"
}

###POST User votes for another choice - should overwrite vote ID and change only voteOptionId

POST http://localhost:8080/votes/castVote
Content-Type: application/json

{
  "userId": "ca3dfed2-71a9-4d1f-8f42-44cdddeca170",
  "pollId": "0b86859b-ac40-46fc-a836-da1028884bac",
  "voteOptionId": "ceb7e0a5-fff3-47f6-95fc-01feb608f661"
}

###GET Get all votes

GET http://localhost:8080/votes/allVotes
Content-Type: application/json

###POST User creates Poll with fixed pollId

POST http://localhost:8080/polls/createPoll
Content-Type: application/json

{
  "question": "What is a better letter?",
  "pollId": "36da6134-6855-4469-a724-ff6a15d0123b",
  "voteOptions": [
    { "caption": "A", "presentationOrder": 1 },
    { "caption": "B", "presentationOrder": 2 }
  ],
  "publishedBy": "73ef6632-20ad-463b-9955-0738601e3f17"
}

###POST Delete poll

POST http://localhost:8080/polls/deletePoll/e3bb00ba-52c6-4fad-9fef-41f5a406cff7
Content-Type: application/json

###GET Get all votes

GET http://localhost:8080/votes/allVotes
Content-Type: application/json