
### POST request to localhost to createUser

POST http://localhost:8080/users/createUser
Content-Type: application/json

{
  "username": "bob",
  "email": "bob@bobinson.com",
  "password": "supersecurepassword"
}

###GET all users again

GET http://localhost:8080/users/allUsers
Content-Type: application/json

### POST request to localhost to create second user

POST http://localhost:8080/users/createUser
Content-Type: application/json

{
  "username": "ben",
  "email": "ben@bobinson.com",
  "password": "supersecurepassword"
}

###GET all users again

GET http://localhost:8080/users/allUsers
Content-Type: application/json

###POST User creates Poll

POST http://localhost:8080/polls/createPoll
Content-Type: application/json

{
  "question": "What is a better letter?",
  "voteOptions": [
    { "caption": "A", "presentationOrder": 1 },
    { "caption": "B", "presentationOrder": 2 }
  ],
  "publishedBy": "73ef6632-20ad-463b-9955-0738601e3f17"
}

###GET all polls

GET http://localhost:8080/polls/allPolls
Content-Type: application/json